name: Docker Build and Push

on:
  push:
    tags:
      - '*'  # 모든 태그에 대해 이 워크플로우를 트리거합니다.
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: arn:aws:iam::654654416925:role/ljh-from-github-to-ecr-role

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract tag name
      id: extract_tag
      shell: bash
      run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: echo image tag
      run: echo $IMAGE_TAG

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update Kustomize Resources
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name "jh-lee99"
        git config --global user.email "jun99h1219@gmail.com"
        git clone https://${PERSONAL_ACCESS_TOKEN}@github.com/jh-lee99/ljh-front-shop-main.git

        cd ljh-front-shop-main/base
        sed -i "s|654654416925.dkr.ecr.ap-northeast-1.amazonaws.com/ljh-front-shop-main:[^ ]*|${{ steps.login-ecr.outputs.registry }}/ljh-front-shop-main:${{ env.IMAGE_TAG }}|g" ljh-front-shop-main-deployment.yaml

        cd ../overlays/dev
        sed -i "s|654654416925.dkr.ecr.ap-northeast-1.amazonaws.com/ljh-front-shop-main:[^ ]*|${{ steps.login-ecr.outputs.registry }}/ljh-front-shop-main:${{ env.IMAGE_TAG }}|g" deployment-patch.yaml

        cd ../../overlays/prod
        sed -i "s|654654416925.dkr.ecr.ap-northeast-1.amazonaws.com/ljh-front-shop-main:[^ ]*|${{ steps.login-ecr.outputs.registry }}/ljh-front-shop-main:${{ env.IMAGE_TAG }}|g" deployment-patch.yaml
        
        # 변경 사항 커밋 및 푸시
        git add .
        git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
        git push origin main
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ vars.AWS_ECR_REPO }}:${{ env.IMAGE_TAG }}
